name: Call check-dist workflow

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  check-dist:
    uses: akv-platform/reusable-workflows/.github/workflows/check-dist.yml@reusable-workflows-update
