name: Validate dotnet

on:
  workflow_dispatch:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - releases/*
    paths-ignore:
      - '**.md'

jobs:
  setup-version:
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        operating-system: [ubuntu-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Run dotnet-installer script
        run: |
          . ./externals/install-dotnet.sh
